export const CONF_LEVELS = ['Public', 'Internal', 'Confidential', 'Restricted', 'Top Secret'];
export const URGENCY_LEVELS = ['Low', 'Normal', 'High', 'Critical'];
export const STATUSES = ['Pending', 'In Progress', 'On Hold', 'Closed', 'Overdue'];
export const DOC_TYPES = [
  'Invoice',
  'Contract',
  'Memo',
  'Policy',
  'Report',
  'Purchase Order',
  'Letter',
  'Incident Report',
];

const DAY = 86400000;
const now = Date.now();
export const d = (offsetDays: number, hour: number = 10) => {
  const t = new Date(now + offsetDays * DAY);
  t.setHours(hour, Math.abs((offsetDays * 17) % 60), 0, 0);
  return t.getTime();
};

export const USERS = [
  {
    id: 'u-chika',
    name: 'Chika Okafor',
    email: 'chika@firstatlantic.com',
    role: 'staff',
    roleLabel: 'Staff Officer',
    dept: 'Operations',
    status: 'Active',
    sso: true,
  },
  {
    id: 'u-david',
    name: 'David Adeyemi',
    email: 'david@firstatlantic.com',
    role: 'supervisor',
    roleLabel: 'Supervisor',
    dept: 'Operations',
    status: 'Active',
    sso: true,
  },
  {
    id: 'u-eniola',
    name: 'Eniola Bakare',
    email: 'eniola@firstatlantic.com',
    role: 'management',
    roleLabel: 'Management',
    dept: 'Executive',
    status: 'Active',
    sso: true,
  },
  {
    id: 'u-bola',
    name: 'Bola Ahmed',
    email: 'bola@firstatlantic.com',
    role: 'clientadmin',
    roleLabel: 'Client Admin',
    dept: 'IT',
    status: 'Active',
    sso: false,
  },
  {
    id: 'u-adaeze',
    name: 'Adaeze Nwosu',
    email: 'adaeze@schulltech.com',
    role: 'platform',
    roleLabel: 'SchullTech Admin',
    dept: 'Platform Ops',
    status: 'Active',
    sso: true,
  },
  {
    id: 'u-femi',
    name: 'Femi Ojo',
    email: 'femi@firstatlantic.com',
    role: 'auditor',
    roleLabel: 'Internal Auditor',
    dept: 'Audit & Compliance',
    status: 'Active',
    sso: false,
  },
  {
    id: 'u-ngozi',
    name: 'Ngozi Eze',
    email: 'ngozi@firstatlantic.com',
    role: 'staff',
    roleLabel: 'Staff Officer',
    dept: 'Finance',
    status: 'Active',
    sso: true,
  },
  {
    id: 'u-tunde',
    name: 'Tunde Balogun',
    email: 'tunde@firstatlantic.com',
    role: 'staff',
    roleLabel: 'Staff Officer',
    dept: 'Operations',
    status: 'Active',
    sso: true,
  },
  {
    id: 'u-amara',
    name: 'Amara Obi',
    email: 'amara@firstatlantic.com',
    role: 'staff',
    roleLabel: 'Staff Officer',
    dept: 'Legal',
    status: 'Suspended',
    sso: false,
  },
  {
    id: 'u-seun',
    name: 'Seun Adesina',
    email: 'seun@firstatlantic.com',
    role: 'staff',
    roleLabel: 'Staff Officer',
    dept: 'Procurement',
    status: 'Active',
    sso: true,
  },
];

export const CABINETS = [
  {
    id: 'cab-hr',
    name: 'Human Resources',
    icon: 'users',
    folders: [
      { id: 'f-hr-contracts', name: 'Employment Contracts' },
      { id: 'f-hr-leave', name: 'Leave & Absence' },
      { id: 'f-hr-policies', name: 'HR Policies' },
    ],
  },
  {
    id: 'cab-fin',
    name: 'Finance',
    icon: 'chart',
    folders: [
      { id: 'f-fin-inv', name: 'Invoices' },
      { id: 'f-fin-budget', name: 'Budgets' },
      { id: 'f-fin-audit', name: 'Audit Reports' },
    ],
  },
  {
    id: 'cab-legal',
    name: 'Legal',
    icon: 'scale',
    folders: [
      { id: 'f-legal-contracts', name: 'Contracts & Agreements' },
      { id: 'f-legal-lit', name: 'Litigation' },
    ],
  },
  {
    id: 'cab-ops',
    name: 'Operations',
    icon: 'gear',
    folders: [
      { id: 'f-ops-sop', name: 'SOPs' },
      { id: 'f-ops-incidents', name: 'Incident Reports' },
      { id: 'f-ops-memos', name: 'Internal Memos' },
    ],
  },
  {
    id: 'cab-proc',
    name: 'Procurement',
    icon: 'cart',
    folders: [
      { id: 'f-proc-po', name: 'Purchase Orders' },
      { id: 'f-proc-vendors', name: 'Vendor Files' },
    ],
  },
];

const mkStages = (arr: any[]) =>
  arr.map((s, i) => ({
    name: s.name,
    assignee: s.assignee,
    state: s.state,
    actedAt: s.actedAt || null,
    comment: s.comment || null,
    sla: s.sla || 48,
  }));

export const DOCUMENTS = [
  {
    id: 'doc-1001',
    title: 'Vendor Invoice — Lagos Office Fit-out (₦48.2M)',
    type: 'Invoice',
    cabinet: 'cab-fin',
    folder: 'f-fin-inv',
    owner: 'u-ngozi',
    assignee: 'u-chika',
    status: 'Pending',
    confidentiality: 'Internal',
    urgency: 'High',
    created: d(-4),
    due: d(1, 17),
    pages: 3,
    version: 2,
    dept: 'Finance',
    workflow: mkStages([
      { name: 'Capture & Classify', assignee: 'u-ngozi', state: 'done', actedAt: d(-4, 11) },
      { name: 'Officer Review', assignee: 'u-chika', state: 'current' },
      { name: 'Supervisor Approval', assignee: 'u-david', state: 'next' },
      { name: 'Payment Processing', assignee: 'u-ngozi', state: 'next' },
      { name: 'Close & File', assignee: 'u-ngozi', state: 'next' },
    ]),
    metadata: {
      'Invoice No.': 'INV-2026-0847',
      Vendor: 'Meridian Interiors Ltd',
      Amount: '₦48,200,000',
      'PO Reference': 'PO-2026-0312',
      'Payment Terms': 'Net 30',
    },
    comments: [
      {
        by: 'u-ngozi',
        at: d(-4, 12),
        text: 'IDU matched this to PO-2026-0312 with 94% confidence. Amounts reconcile.',
      },
    ],
    redactions: [],
    signatures: [],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1002',
    title: 'Employment Contract — Senior Analyst, M. Danjuma',
    type: 'Contract',
    cabinet: 'cab-hr',
    folder: 'f-hr-contracts',
    owner: 'u-chika',
    assignee: 'u-chika',
    status: 'Pending',
    confidentiality: 'Confidential',
    urgency: 'Critical',
    created: d(-6),
    due: d(-1, 12),
    pages: 8,
    version: 1,
    dept: 'Operations',
    workflow: mkStages([
      { name: 'Draft & Upload', assignee: 'u-chika', state: 'done', actedAt: d(-6, 9) },
      {
        name: 'Legal Review',
        assignee: 'u-amara',
        state: 'done',
        actedAt: d(-3, 15),
        comment: 'Clause 7 amended per policy.',
      },
      { name: 'Officer Sign-off', assignee: 'u-chika', state: 'current' },
      { name: 'HR Countersign', assignee: 'u-david', state: 'next' },
    ]),
    metadata: {
      Employee: 'Musa Danjuma',
      Grade: 'SA-3',
      'Start Date': '01 Aug 2026',
      'Contract Type': 'Permanent',
    },
    comments: [
      {
        by: 'u-amara',
        at: d(-3, 15),
        text: 'Legal review complete. Ready for signature — note the revised notice period in clause 7.',
      },
    ],
    redactions: [],
    signatures: [
      { field: 'Employer Representative', page: 1, x: 8, y: 78, w: 40, h: 8, signedBy: null },
    ],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1003',
    title: 'Q2 Operations Incident Report — ATM Network Outage',
    type: 'Incident Report',
    cabinet: 'cab-ops',
    folder: 'f-ops-incidents',
    owner: 'u-tunde',
    assignee: 'u-chika',
    status: 'In Progress',
    confidentiality: 'Restricted',
    urgency: 'High',
    created: d(-9),
    due: d(2, 16),
    pages: 12,
    version: 3,
    dept: 'Operations',
    workflow: mkStages([
      { name: 'Incident Capture', assignee: 'u-tunde', state: 'done', actedAt: d(-9, 8) },
      { name: 'Root-Cause Review', assignee: 'u-chika', state: 'current' },
      { name: 'Supervisor Approval', assignee: 'u-david', state: 'next' },
      { name: 'Management Notify', assignee: 'u-eniola', state: 'next' },
    ]),
    metadata: {
      'Incident ID': 'INC-2026-0091',
      Severity: 'Sev-2',
      Duration: '4h 12m',
      'Affected Sites': '37 branches',
    },
    comments: [
      {
        by: 'u-tunde',
        at: d(-8, 10),
        text: 'Attached the network vendor RCA. Sections 4–6 need officer validation.',
      },
      {
        by: 'u-david',
        at: d(-5, 14),
        text: 'Please prioritise — management wants this before the quarterly review.',
      },
    ],
    redactions: [
      {
        page: 1,
        x: 12,
        y: 46,
        w: 55,
        h: 5,
        reason: 'Customer account identifiers',
        released: false,
      },
    ],
    signatures: [],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1004',
    title: 'Master Services Agreement — CloudCore Nigeria',
    type: 'Contract',
    cabinet: 'cab-legal',
    folder: 'f-legal-contracts',
    owner: 'u-amara',
    assignee: 'u-david',
    status: 'Pending',
    confidentiality: 'Confidential',
    urgency: 'Normal',
    created: d(-3),
    due: d(3, 12),
    pages: 24,
    version: 1,
    dept: 'Legal',
    workflow: mkStages([
      { name: 'Draft & Upload', assignee: 'u-amara', state: 'done', actedAt: d(-3, 9) },
      {
        name: 'Commercial Review',
        assignee: 'u-chika',
        state: 'done',
        actedAt: d(-2, 16),
        comment: 'Pricing schedule verified.',
      },
      { name: 'Supervisor Approval', assignee: 'u-david', state: 'current' },
      { name: 'Counter-signature', assignee: 'u-eniola', state: 'next' },
    ]),
    metadata: {
      Counterparty: 'CloudCore Nigeria Ltd',
      Value: '₦220,000,000 / yr',
      Term: '36 months',
      Renewal: 'Auto, 12 mo',
    },
    comments: [],
    redactions: [],
    signatures: [
      { field: 'Authorised Signatory', page: 1, x: 8, y: 80, w: 40, h: 8, signedBy: null },
    ],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1005',
    title: 'Purchase Order — 120× Thin Client Workstations',
    type: 'Purchase Order',
    cabinet: 'cab-proc',
    folder: 'f-proc-po',
    owner: 'u-seun',
    assignee: 'u-chika',
    status: 'Overdue',
    confidentiality: 'Internal',
    urgency: 'Critical',
    created: d(-12),
    due: d(-3, 10),
    pages: 2,
    version: 1,
    dept: 'Procurement',
    workflow: mkStages([
      { name: 'Requisition', assignee: 'u-seun', state: 'done', actedAt: d(-12, 9) },
      {
        name: 'Budget Check',
        assignee: 'u-ngozi',
        state: 'done',
        actedAt: d(-10, 13),
        comment: 'Within CAPEX envelope.',
      },
      { name: 'Officer Verification', assignee: 'u-chika', state: 'current' },
      { name: 'Supervisor Approval', assignee: 'u-david', state: 'next' },
    ]),
    metadata: {
      'PO Number': 'PO-2026-0355',
      Vendor: 'TechHub Distribution',
      Amount: '₦31,440,000',
      Delivery: 'HQ Annex, Victoria Island',
    },
    comments: [
      {
        by: 'u-seun',
        at: d(-7, 11),
        text: 'Vendor is asking for a delivery date — can we expedite verification?',
      },
    ],
    redactions: [],
    signatures: [],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1006',
    title: 'Revised Remote Work Policy v3',
    type: 'Policy',
    cabinet: 'cab-hr',
    folder: 'f-hr-policies',
    owner: 'u-bola',
    assignee: 'u-chika',
    status: 'In Progress',
    confidentiality: 'Public',
    urgency: 'Low',
    created: d(-15),
    due: d(6, 10),
    pages: 6,
    version: 3,
    dept: 'Operations',
    workflow: mkStages([
      { name: 'Policy Draft', assignee: 'u-bola', state: 'done', actedAt: d(-15, 10) },
      { name: 'Staff Consultation', assignee: 'u-chika', state: 'current' },
      { name: 'Management Approval', assignee: 'u-eniola', state: 'next' },
      { name: 'Publish as Circular', assignee: 'u-bola', state: 'next' },
    ]),
    metadata: { 'Policy Ref': 'POL-HR-014', Effective: '01 Sep 2026', Supersedes: 'v2 (2024)' },
    comments: [],
    redactions: [],
    signatures: [],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1007',
    title: 'FY2026 Half-Year Budget Variance Report',
    type: 'Report',
    cabinet: 'cab-fin',
    folder: 'f-fin-budget',
    owner: 'u-ngozi',
    assignee: 'u-david',
    status: 'In Progress',
    confidentiality: 'Restricted',
    urgency: 'High',
    created: d(-5),
    due: d(4, 15),
    pages: 18,
    version: 1,
    dept: 'Finance',
    workflow: mkStages([
      { name: 'Compile', assignee: 'u-ngozi', state: 'done', actedAt: d(-5, 9) },
      { name: 'Supervisor Review', assignee: 'u-david', state: 'current' },
      { name: 'Management Sign-off', assignee: 'u-eniola', state: 'next' },
    ]),
    metadata: {
      Period: 'Jan–Jun 2026',
      Variance: '-3.8% vs plan',
      'Prepared by': 'Finance Analytics',
    },
    comments: [],
    redactions: [],
    signatures: [],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1008',
    title: 'Branch Expansion Memo — Port Harcourt South',
    type: 'Memo',
    cabinet: 'cab-ops',
    folder: 'f-ops-memos',
    owner: 'u-chika',
    assignee: 'u-chika',
    status: 'Closed',
    confidentiality: 'Internal',
    urgency: 'Normal',
    created: d(-20),
    due: d(-14, 12),
    pages: 4,
    version: 1,
    dept: 'Operations',
    closedAt: d(-15, 16),
    workflow: mkStages([
      { name: 'Draft', assignee: 'u-chika', state: 'done', actedAt: d(-20, 9) },
      {
        name: 'Supervisor Approval',
        assignee: 'u-david',
        state: 'done',
        actedAt: d(-16, 11),
        comment: 'Approved with budget note.',
      },
      { name: 'Close & File', assignee: 'u-chika', state: 'done', actedAt: d(-15, 16) },
    ]),
    metadata: { 'Memo Ref': 'MEM-OPS-2026-112', Decision: 'Approved' },
    comments: [],
    redactions: [],
    signatures: [],
    sealed: true,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
  },
  {
    id: 'doc-1009',
    title: 'Litigation Brief — Suit FHC/L/CS/882 (Restricted)',
    type: 'Report',
    cabinet: 'cab-legal',
    folder: 'f-legal-lit',
    owner: 'u-amara',
    assignee: 'u-amara',
    status: 'On Hold',
    confidentiality: 'Top Secret',
    urgency: 'High',
    created: d(-30),
    due: d(10, 12),
    pages: 44,
    version: 5,
    dept: 'Legal',
    workflow: mkStages([
      { name: 'Case Intake', assignee: 'u-amara', state: 'done', actedAt: d(-30, 9) },
      { name: 'External Counsel Review', assignee: 'u-amara', state: 'current' },
      { name: 'Executive Briefing', assignee: 'u-eniola', state: 'next' },
    ]),
    metadata: {
      'Suit No.': 'FHC/L/CS/882/2026',
      'Legal Hold': 'Yes',
      'External Counsel': 'Adebayo & Partners',
    },
    comments: [],
    redactions: [],
    signatures: [],
    sealed: false,
    locked: null,
    legalHold: true,
    restrictedTo: ['u-amara', 'u-eniola', 'u-femi'],
    closedAt: undefined,
  },
  {
    id: 'doc-1010',
    title: 'Vendor Onboarding Pack — SwiftLogistics',
    type: 'Contract',
    cabinet: 'cab-proc',
    folder: 'f-proc-vendors',
    owner: 'u-seun',
    assignee: 'u-david',
    status: 'Overdue',
    confidentiality: 'Internal',
    urgency: 'Normal',
    created: d(-18),
    due: d(-5, 12),
    pages: 15,
    version: 2,
    dept: 'Procurement',
    workflow: mkStages([
      { name: 'Vendor Submission', assignee: 'u-seun', state: 'done', actedAt: d(-18, 9) },
      {
        name: 'Due Diligence',
        assignee: 'u-tunde',
        state: 'done',
        actedAt: d(-9, 14),
        comment: 'KYC verified.',
      },
      { name: 'Supervisor Approval', assignee: 'u-david', state: 'current' },
    ]),
    metadata: { 'Vendor ID': 'VEN-2026-078', Category: 'Logistics', 'Risk Rating': 'Medium' },
    comments: [],
    redactions: [],
    signatures: [],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1011',
    title: 'Staff Leave Reconciliation — June 2026',
    type: 'Report',
    cabinet: 'cab-hr',
    folder: 'f-hr-leave',
    owner: 'u-chika',
    assignee: 'u-chika',
    status: 'Closed',
    confidentiality: 'Internal',
    urgency: 'Low',
    created: d(-11),
    due: d(-6, 10),
    pages: 5,
    version: 1,
    dept: 'Operations',
    closedAt: d(-7, 10),
    workflow: mkStages([
      { name: 'Compile', assignee: 'u-chika', state: 'done', actedAt: d(-11, 9) },
      { name: 'HR Validation', assignee: 'u-ngozi', state: 'done', actedAt: d(-8, 12) },
      { name: 'Close & File', assignee: 'u-chika', state: 'done', actedAt: d(-7, 10) },
    ]),
    metadata: { Period: 'June 2026' },
    comments: [],
    redactions: [],
    signatures: [],
    sealed: true,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
  },
  {
    id: 'doc-1012',
    title: 'Facility Maintenance SOP — Generator Handover',
    type: 'Policy',
    cabinet: 'cab-ops',
    folder: 'f-ops-sop',
    owner: 'u-tunde',
    assignee: 'u-tunde',
    status: 'In Progress',
    confidentiality: 'Internal',
    urgency: 'Normal',
    created: d(-8),
    due: d(5, 10),
    pages: 9,
    version: 1,
    dept: 'Operations',
    workflow: mkStages([
      { name: 'Draft', assignee: 'u-tunde', state: 'done', actedAt: d(-8, 9) },
      { name: 'Peer Review', assignee: 'u-chika', state: 'current' },
      { name: 'Supervisor Approval', assignee: 'u-david', state: 'next' },
    ]),
    metadata: { 'SOP Ref': 'SOP-FM-031' },
    comments: [],
    redactions: [],
    signatures: [],
    sealed: false,
    locked: 'u-tunde',
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
  {
    id: 'doc-1013',
    title: 'External Audit Findings — IT General Controls',
    type: 'Report',
    cabinet: 'cab-fin',
    folder: 'f-fin-audit',
    owner: 'u-femi',
    assignee: 'u-femi',
    status: 'In Progress',
    confidentiality: 'Restricted',
    urgency: 'High',
    created: d(-14),
    due: d(7, 12),
    pages: 22,
    version: 2,
    dept: 'Audit & Compliance',
    workflow: mkStages([
      { name: 'Fieldwork', assignee: 'u-femi', state: 'done', actedAt: d(-14, 9) },
      { name: 'Findings Draft', assignee: 'u-femi', state: 'current' },
      { name: 'Management Response', assignee: 'u-eniola', state: 'next' },
    ]),
    metadata: { 'Audit Ref': 'AUD-2026-IT-04', Findings: '3 (1 high, 2 medium)' },
    comments: [],
    redactions: [],
    signatures: [],
    sealed: false,
    locked: null,
    restrictedTo: undefined,
    legalHold: false,
    closedAt: undefined,
  },
];

export const NOTIFICATIONS = [
  {
    id: 'n1',
    user: 'u-chika',
    type: 'task',
    text: 'Employment Contract — M. Danjuma is overdue for your sign-off (SLA breached).',
    at: d(0, 8),
    read: false,
    docId: 'doc-1002',
  },
  {
    id: 'n2',
    user: 'u-chika',
    type: 'sla',
    text: 'PO-2026-0355 breached its SLA 3 days ago. Escalation to David Adeyemi triggered.',
    at: d(0, 7),
    read: false,
    docId: 'doc-1005',
  },
  {
    id: 'n3',
    user: 'u-chika',
    type: 'comment',
    text: 'David Adeyemi commented on the ATM Network Outage report.',
    at: d(-1, 14),
    read: false,
    docId: 'doc-1003',
  },
  {
    id: 'n4',
    user: 'u-chika',
    type: 'circular',
    text: 'New circular: “Updated Clean Desk & Confidentiality Directive” requires acknowledgement.',
    at: d(-1, 9),
    read: false,
    circularId: 'cir-2',
  },
  {
    id: 'n5',
    user: 'u-chika',
    type: 'workflow',
    text: 'Legal Review completed on Employment Contract — routed to you for sign-off.',
    at: d(-3, 15),
    read: true,
    docId: 'doc-1002',
  },
  {
    id: 'n6',
    user: 'u-chika',
    type: 'task',
    text: 'MSA — CloudCore Nigeria: your commercial review was accepted.',
    at: d(-2, 16),
    read: true,
    docId: 'doc-1004',
  },
  {
    id: 'n7',
    user: 'u-david',
    type: 'sla',
    text: 'Vendor Onboarding — SwiftLogistics has been awaiting your approval for 5 days (SLA breach).',
    at: d(0, 8),
    read: false,
    docId: 'doc-1010',
  },
  {
    id: 'n8',
    user: 'u-david',
    type: 'task',
    text: 'MSA — CloudCore Nigeria routed for supervisor approval.',
    at: d(-2, 16),
    read: false,
    docId: 'doc-1004',
  },
  {
    id: 'n9',
    user: 'u-david',
    type: 'workflow',
    text: 'Escalation: PO-2026-0355 breached SLA at Officer Verification (Chika Okafor).',
    at: d(-3, 9),
    read: true,
    docId: 'doc-1005',
  },
  {
    id: 'n10',
    user: 'u-eniola',
    type: 'report',
    text: 'H1 Budget Variance Report will reach you after supervisor review.',
    at: d(-1, 10),
    read: false,
    docId: 'doc-1007',
  },
  {
    id: 'n11',
    user: 'u-bola',
    type: 'admin',
    text: '2 users have not completed SSO enrolment. Review in Users & Roles.',
    at: d(-1, 9),
    read: false,
  },
  {
    id: 'n12',
    user: 'u-adaeze',
    type: 'platform',
    text: 'Tenant “Kano State IRS” exceeded 85% of storage entitlement.',
    at: d(0, 6),
    read: false,
  },
  {
    id: 'n13',
    user: 'u-femi',
    type: 'audit',
    text: 'SoD exception: same user uploaded and approved MEM-OPS-2026-112.',
    at: d(-2, 11),
    read: false,
    docId: 'doc-1008',
  },
];

export const CIRCULARS = [
  {
    id: 'cir-1',
    title: 'H2 2026 Performance Review Cycle — Timeline & Templates',
    body: 'The half-year performance review cycle opens on 15 July 2026. All officers should complete self-assessments in the HR cabinet by 22 July. Supervisors must complete reviews by 5 August. Templates are filed under Human Resources › HR Policies.',
    published: d(-2, 9),
    by: 'u-bola',
    requiresAck: true,
    ackBy: ['u-david'],
    audience: 'All Staff',
  },
  {
    id: 'cir-2',
    title: 'Updated Clean Desk & Confidentiality Directive',
    body: 'Effective immediately: documents classified Confidential or above must not be left unattended on desks or shared screens. Printing of Restricted documents now requires supervisor approval, and all print jobs are watermarked and audited. Violations will be logged as compliance exceptions.',
    published: d(-1, 9),
    by: 'u-bola',
    requiresAck: true,
    ackBy: [],
    audience: 'All Staff',
  },
  {
    id: 'cir-3',
    title: 'Scheduled Maintenance — EDMS Platform, Sunday 02:00–04:00 WAT',
    body: 'The EDMS platform will undergo scheduled maintenance this Sunday between 02:00 and 04:00 WAT. Document upload and signing will be unavailable. In-flight workflows are not affected; SLA timers are paused during the window.',
    published: d(-5, 16),
    by: 'u-adaeze',
    requiresAck: false,
    ackBy: [],
    audience: 'All Tenants',
  },
  {
    id: 'cir-4',
    title: 'New Procurement Threshold Matrix (Effective 01 Aug)',
    body: 'Approval thresholds have been revised: purchases above ₦25M now require dual supervisor approval, and above ₦100M require management sign-off with maker-checker enforced. The Procurement workflow has been updated to v4 to reflect this.',
    published: d(-9, 11),
    by: 'u-bola',
    requiresAck: true,
    ackBy: ['u-chika', 'u-david', 'u-seun'],
    audience: 'Procurement, Finance',
  },
];

export const WORKFLOWS = [
  {
    id: 'wf-1',
    name: 'Invoice Approval',
    version: 4,
    status: 'Published',
    updated: d(-6),
    appliedTo: 'Finance › Invoices',
    nodes: [
      {
        id: 'n1',
        type: 'start',
        name: 'Capture',
        x: 30,
        y: 40,
        summary: 'Upload / email-in / scan',
      },
      {
        id: 'n2',
        type: 'review',
        name: 'Officer Review',
        x: 240,
        y: 40,
        summary: 'Role: Staff Officer · SLA 48h',
        sla: 48,
        role: 'Staff Officer',
        escalation: 'Supervisor',
      },
      {
        id: 'n3',
        type: 'condition',
        name: 'Amount > ₦25M?',
        x: 450,
        y: 40,
        summary: 'Branch on invoice amount',
      },
      {
        id: 'n4',
        type: 'approval',
        name: 'Dual Approval',
        x: 660,
        y: 10,
        summary: 'Role: Supervisor ×2 · SoD',
        sla: 72,
        role: 'Supervisor',
        controls: 'Maker-checker',
      },
      {
        id: 'n5',
        type: 'approval',
        name: 'Supervisor Approval',
        x: 660,
        y: 110,
        summary: 'Role: Supervisor · SLA 72h',
        sla: 72,
        role: 'Supervisor',
      },
      {
        id: 'n6',
        type: 'close',
        name: 'File & Close',
        x: 870,
        y: 60,
        summary: 'Retention: 7 years',
      },
    ],
    edges: [
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n3', 'n4', 'Yes'],
      ['n3', 'n5', 'No'],
      ['n4', 'n6'],
      ['n5', 'n6'],
    ],
  },
  {
    id: 'wf-2',
    name: 'Contract Lifecycle',
    version: 2,
    status: 'Published',
    updated: d(-20),
    appliedTo: 'Legal › Contracts & Agreements',
    nodes: [
      { id: 'n1', type: 'start', name: 'Draft', x: 30, y: 60, summary: 'Contract draft upload' },
      {
        id: 'n2',
        type: 'review',
        name: 'Legal Review',
        x: 240,
        y: 60,
        summary: 'Role: Legal · SLA 96h',
        sla: 96,
        role: 'Legal Officer',
      },
      {
        id: 'n3',
        type: 'approval',
        name: 'Supervisor Approval',
        x: 450,
        y: 60,
        summary: 'Role: Supervisor · SLA 48h',
        sla: 48,
        role: 'Supervisor',
      },
      {
        id: 'n4',
        type: 'sign',
        name: 'Signatures',
        x: 660,
        y: 60,
        summary: 'Multi-party, sequential',
      },
      {
        id: 'n5',
        type: 'close',
        name: 'Seal & File',
        x: 870,
        y: 60,
        summary: 'Tamper-evident seal',
      },
    ],
    edges: [
      ['n1', 'n2'],
      ['n2', 'n3'],
      ['n3', 'n4'],
      ['n4', 'n5'],
    ],
  },
  {
    id: 'wf-3',
    name: 'Incident Escalation',
    version: 1,
    status: 'Draft',
    updated: d(-1),
    appliedTo: '—',
    nodes: [
      {
        id: 'n1',
        type: 'start',
        name: 'Incident Logged',
        x: 30,
        y: 60,
        summary: 'From incident form',
      },
      {
        id: 'n2',
        type: 'parallel',
        name: 'Parallel Review',
        x: 240,
        y: 60,
        summary: 'Ops + Risk simultaneously',
      },
      {
        id: 'n3',
        type: 'notify',
        name: 'Notify Management',
        x: 450,
        y: 60,
        summary: 'On Sev-1/Sev-2',
      },
    ],
    edges: [
      ['n1', 'n2'],
      ['n2', 'n3'],
    ],
  },
];

export const ROLES_MATRIX = [
  {
    role: 'Staff Officer',
    perms: {
      view: true,
      upload: true,
      approve: false,
      sign: true,
      redact: false,
      admin: false,
      audit: false,
    },
  },
  {
    role: 'Supervisor',
    perms: {
      view: true,
      upload: true,
      approve: true,
      sign: true,
      redact: true,
      admin: false,
      audit: false,
    },
  },
  {
    role: 'Management',
    perms: {
      view: true,
      upload: false,
      approve: true,
      sign: true,
      redact: false,
      admin: false,
      audit: false,
    },
  },
  {
    role: 'Client Admin',
    perms: {
      view: true,
      upload: true,
      approve: false,
      sign: false,
      redact: false,
      admin: true,
      audit: true,
    },
  },
  {
    role: 'Internal Auditor',
    perms: {
      view: true,
      upload: false,
      approve: false,
      sign: false,
      redact: false,
      admin: false,
      audit: true,
    },
  },
];

export const TENANTS = [
  {
    id: 't-1',
    name: 'First Atlantic Bank',
    model: 'White-label',
    plan: 'Enterprise',
    status: 'Active',
    users: 1240,
    storageGb: 812,
    storageLimit: 1024,
    health: 'ok',
    domain: 'edms.firstatlantic.com',
    since: '2025-03',
    mrr: 14500,
  },
  {
    id: 't-2',
    name: 'Kano State IRS',
    model: 'White-label',
    plan: 'Enterprise',
    status: 'Active',
    users: 640,
    storageGb: 442,
    storageLimit: 512,
    health: 'warn',
    domain: 'docs.kanoirs.gov.ng',
    since: '2025-08',
    mrr: 9800,
  },
  {
    id: 't-3',
    name: 'MedTrust HMO',
    model: 'Subscription',
    plan: 'Professional',
    status: 'Active',
    users: 185,
    storageGb: 96,
    storageLimit: 256,
    health: 'ok',
    domain: 'medtrust.schulltech.app',
    since: '2025-11',
    mrr: 3200,
  },
  {
    id: 't-4',
    name: 'Zenith Microfinance',
    model: 'Subscription',
    plan: 'Professional',
    status: 'Trial',
    users: 42,
    storageGb: 11,
    storageLimit: 128,
    health: 'ok',
    domain: 'zenithmfb.schulltech.app',
    since: '2026-06',
    mrr: 0,
  },
  {
    id: 't-5',
    name: 'Lagos Free Zone Co.',
    model: 'Subscription',
    plan: 'Starter',
    status: 'Active',
    users: 66,
    storageGb: 34,
    storageLimit: 64,
    health: 'ok',
    domain: 'lfzc.schulltech.app',
    since: '2026-01',
    mrr: 1100,
  },
  {
    id: 't-6',
    name: 'Harmony Pensions',
    model: 'White-label',
    plan: 'Enterprise',
    status: 'Suspended',
    users: 310,
    storageGb: 205,
    storageLimit: 512,
    health: 'down',
    domain: 'edocs.harmonypensions.com',
    since: '2025-05',
    mrr: 8400,
  },
];

export const FINDINGS = [
  {
    id: 'fd-1',
    ref: 'FND-2026-014',
    title: 'SoD conflict: uploader approved own memo',
    severity: 'High',
    status: 'Open',
    owner: 'u-david',
    raised: d(-2),
    due: d(12),
    control: 'Segregation of Duties',
    detail:
      'MEM-OPS-2026-112 was uploaded and approved within the same session by the same user account. Maker-checker control did not trigger because the workflow version predates control rollout.',
    responses: [],
  },
  {
    id: 'fd-2',
    ref: 'FND-2026-013',
    title: 'Restricted document printed without watermark',
    severity: 'Medium',
    status: 'In Remediation',
    owner: 'u-bola',
    raised: d(-8),
    due: d(6),
    control: 'Confidentiality Controls',
    detail:
      'Print event for AUD-2026-IT-04 on 30 June lacked the dynamic watermark overlay. Print service configuration has been corrected; verification pending.',
    responses: [
      {
        by: 'u-bola',
        at: d(-4),
        text: 'Watermark service redeployed with correct tenant config. Requesting re-test.',
      },
    ],
  },
  {
    id: 'fd-3',
    ref: 'FND-2026-011',
    title: 'Stale user accounts with active sessions',
    severity: 'Medium',
    status: 'Open',
    owner: 'u-bola',
    raised: d(-15),
    due: d(1),
    control: 'Access Management',
    detail: '3 accounts inactive for over 90 days retain active roles, one with approval rights.',
    responses: [],
  },
  {
    id: 'fd-4',
    ref: 'FND-2026-009',
    title: 'Retention schedule not applied to closed litigation files',
    severity: 'Low',
    status: 'Closed',
    owner: 'u-amara',
    raised: d(-30),
    due: d(-10),
    closedAt: d(-9),
    control: 'Records Retention',
    detail:
      'Closed litigation files older than the schedule remained in the active cabinet. Retention job re-run; files archived.',
    responses: [{ by: 'u-amara', at: d(-11), text: 'Retention job completed. Evidence attached.' }],
  },
];

export const seedAudit = [
  {
    at: d(0, 8),
    user: 'u-chika',
    action: 'LOGIN',
    target: 'Session',
    detail: 'Signed in via SSO (Okta)',
    tenant: 't-1',
  },
  {
    at: d(-1, 16),
    user: 'u-david',
    action: 'APPROVE',
    target: 'doc-1008',
    detail: 'Approved Branch Expansion Memo',
    tenant: 't-1',
  },
  {
    at: d(-1, 14),
    user: 'u-david',
    action: 'COMMENT',
    target: 'doc-1003',
    detail: 'Commented on ATM Network Outage report',
    tenant: 't-1',
  },
  {
    at: d(-2, 10),
    user: 'u-bola',
    action: 'PUBLISH_CIRCULAR',
    target: 'cir-2',
    detail: 'Published Clean Desk Directive',
    tenant: 't-1',
  },
  {
    at: d(-2, 9),
    user: 'u-ngozi',
    action: 'UPLOAD',
    target: 'doc-1007',
    detail: 'Uploaded H1 Budget Variance Report',
    tenant: 't-1',
  },
  {
    at: d(-3, 15),
    user: 'u-amara',
    action: 'STAGE_COMPLETE',
    target: 'doc-1002',
    detail: 'Completed Legal Review',
    tenant: 't-1',
  },
  {
    at: d(-3, 9),
    user: 'system',
    action: 'SLA_ESCALATION',
    target: 'doc-1005',
    detail: 'SLA breach escalated to supervisor',
    tenant: 't-1',
  },
  {
    at: d(-4, 11),
    user: 'u-ngozi',
    action: 'UPLOAD',
    target: 'doc-1001',
    detail: 'Uploaded vendor invoice (IDU confidence 94%)',
    tenant: 't-1',
  },
  {
    at: d(-5, 13),
    user: 'u-adaeze',
    action: 'TENANT_CONFIG',
    target: 't-2',
    detail: 'Raised storage soft-limit alert threshold to 85%',
    tenant: 'platform',
  },
  {
    at: d(-6, 10),
    user: 'u-bola',
    action: 'WORKFLOW_PUBLISH',
    target: 'wf-1',
    detail: 'Published Invoice Approval v4',
    tenant: 't-1',
  },
  {
    at: d(-8, 15),
    user: 'u-femi',
    action: 'AUDIT_EXPORT',
    target: 'Audit Log',
    detail: 'Exported Q2 access review extract',
    tenant: 't-1',
  },
  {
    at: d(-9, 8),
    user: 'u-tunde',
    action: 'UPLOAD',
    target: 'doc-1003',
    detail: 'Filed incident report INC-2026-0091',
    tenant: 't-1',
  },
];

export const POLICIES = {
  confidentiality: [
    {
      level: 'Public',
      desc: 'No restriction. May be shared externally.',
      watermark: false,
      download: true,
      print: true,
    },
    {
      level: 'Internal',
      desc: 'Staff only. External sharing requires approval.',
      watermark: false,
      download: true,
      print: true,
    },
    {
      level: 'Confidential',
      desc: 'Named roles only. Sharing audited.',
      watermark: true,
      download: true,
      print: true,
    },
    {
      level: 'Restricted',
      desc: 'Explicit grant per user. Watermarked. Print requires supervisor approval.',
      watermark: true,
      download: false,
      print: false,
    },
    {
      level: 'Top Secret',
      desc: 'Executive grant only. View-only, watermarked, step-up auth to open.',
      watermark: true,
      download: false,
      print: false,
    },
  ],
  urgency: [
    { level: 'Low', sla: 120, color: 'muted' },
    { level: 'Normal', sla: 72, color: 'progress' },
    { level: 'High', sla: 48, color: 'accent' },
    { level: 'Critical', sla: 24, color: 'overdue' },
  ],
  retention: [
    { type: 'Invoices & payment records', years: 7, action: 'Archive then destroy' },
    { type: 'Contracts', years: 10, action: 'Archive after expiry + 6 years' },
    { type: 'HR / employee records', years: 6, action: 'Archive after exit' },
    { type: 'Audit reports', years: 10, action: 'Permanent archive' },
    { type: 'Litigation (legal hold)', years: 0, action: 'Hold — no destruction while active' },
  ],
  controls: [
    { rule: 'Maker-checker on payments > ₦5M', scope: 'Finance', enabled: true },
    { rule: 'SoD: uploader cannot approve own document', scope: 'All cabinets', enabled: true },
    { rule: 'Dual approval on purchases > ₦25M', scope: 'Procurement', enabled: true },
    { rule: 'Step-up auth for Top Secret access', scope: 'All cabinets', enabled: true },
    { rule: 'Supervisor approval to print Restricted', scope: 'All cabinets', enabled: false },
  ],
};

export const FEATURE_FLAGS = [
  {
    id: 'ff-1',
    name: 'AI Semantic Search v2',
    stage: 'GA',
    rollout: 100,
    desc: 'Vector search across OCR text layer.',
  },
  {
    id: 'ff-2',
    name: 'IDU Auto-classification',
    stage: 'Beta',
    rollout: 60,
    desc: 'Automatic doc-type + cabinet suggestion at ingest.',
  },
  {
    id: 'ff-3',
    name: 'Redaction AI Suggestions',
    stage: 'Beta',
    rollout: 35,
    desc: 'Detects PII/account numbers for redaction.',
  },
  {
    id: 'ff-4',
    name: 'Dark Theme',
    stage: 'Preview',
    rollout: 15,
    desc: 'Optional dark theme per user.',
  },
  {
    id: 'ff-5',
    name: 'Mobile Web Dashboards',
    stage: 'Internal',
    rollout: 5,
    desc: 'Read-only dashboards under 768px.',
  },
];

export const PLANS = [
  {
    name: 'Starter',
    priceMo: 450,
    users: 100,
    storageGb: 64,
    features: ['Core EDMS', 'Standard workflows', 'Email support'],
  },
  {
    name: 'Professional',
    priceMo: 1600,
    users: 500,
    storageGb: 256,
    features: [
      'Everything in Starter',
      'Workflow designer',
      'IDU classification',
      'E-signature',
      'API access',
    ],
  },
  {
    name: 'Enterprise',
    priceMo: 6000,
    users: 5000,
    storageGb: 1024,
    features: [
      'Everything in Professional',
      'White-label & custom domain',
      'SSO / SCIM',
      'Redaction AI',
      'Dedicated support & SLA',
    ],
  },
];

export const SEED = {
  v: 3,
  users: USERS,
  cabinets: CABINETS,
  docTypes: DOC_TYPES,
  documents: DOCUMENTS,
  notifications: NOTIFICATIONS,
  circulars: CIRCULARS,
  workflows: WORKFLOWS,
  rolesMatrix: ROLES_MATRIX,
  tenants: TENANTS,
  findings: FINDINGS,
  audit: seedAudit,
  policies: POLICIES,
  featureFlags: FEATURE_FLAGS,
  plans: PLANS,
  savedSearches: [
    { id: 'ss-1', name: 'My overdue items', q: '', facets: { status: ['Overdue'] } },
    {
      id: 'ss-2',
      name: 'Restricted finance docs',
      q: '',
      facets: { cabinet: ['cab-fin'], confidentiality: ['Restricted'] },
    },
  ],
  branding: {
    appName: 'SchullTech EDMS',
    tenantName: 'First Atlantic Bank',
    primary: '#1F3864',
    primaryLight: '#2E5496',
    accent: '#C55A11',
    logoText: 'S',
  },
  prefs: { density: 'comfortable', theme: 'light' },
  session: null as string | null,
  seq: 2000,
};
